"""empty message

Revision ID: 2b39626a3551
Revises: 776844323bbd
Create Date: 2023-02-09 15:45:11.522958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b39626a3551'
down_revision = '776844323bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=100), nullable=True))
        batch_op.drop_column('publication_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('year')

    # ### end Alembic commands ###
