"""empty message

Revision ID: 4eca2d2e4ffa
Revises: 2b39626a3551
Create Date: 2023-02-09 15:56:23.818848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eca2d2e4ffa'
down_revision = '2b39626a3551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_release', sa.String(length=100), nullable=True))
        batch_op.drop_column('year')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('year_of_release')

    # ### end Alembic commands ###
