"""empty message

Revision ID: f04cfd30d2db
Revises: 4eca2d2e4ffa
Create Date: 2023-02-09 18:52:38.062337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04cfd30d2db'
down_revision = '4eca2d2e4ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('num_pages',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('format',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('year_of_release',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('year_of_release',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('format',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('num_pages',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
